name: flutter_color_picker
description: A HSV color picker inspired by chrome devtools and a material color picker for your flutter app.
version: 0.0.1
author: "ysdy44 <ysdy44@outlook.com>"
homepage: https://github.com/ysdy44/flutter_color_picker

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"